@token = BQB5WvlghweKiWS2-Ljkp5j0f86wyyNWEA4gzIoArnqF6wfj_pCv5z9-Ty0jrQEiDLo5R5w_-GEfOzIf3eBm7zrCVewXY2IfTz3s1SEGp6ExWeyHfX51F5YqwQ6NNa9sae41NYQSfNn8rXWg9Qm069wxvX3akvqBHwwEXEXvWKTUbBpqzeZ24bjwpVyy57ACo88AwA/

###

POST https://accounts.spotify.com/api/token HTTP/1.1
Authorization: Basic Zjg0MjNlOTFhY2QxNGEzNTgwNzQ5ZjBhNjAzNmNlOTk6M2NkZDZlYTdmMjFkNGYwZGFiODI2YmJjMmQ2Zjg0NWE=
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials

###

GET https://api.spotify.com/v1/albums/2up3OPMp9Tb4dAKM2erWXQ
Authorization: Bearer {{token}}