@token = BQBZ0X09yKezvwiuJwCDBaPh6U5M6PS2zfXdgbvomG7ti6PkkJL7KiU_TOH4kUF82Q7hHuOl7NGogfQROci81__JzR-4pi3CvQCmElBWZQ1DQU0bLCDYQ0g6HrK3CknrDa8QOJGyDjjwqYovAz3sjuGdVebdVvepNEJ6lGJoCTdixtVhw3Ez_g88Yi--4Vs5s_RqOg

###

POST https://accounts.spotify.com/api/token HTTP/1.1
Authorization: Basic Zjg0MjNlOTFhY2QxNGEzNTgwNzQ5ZjBhNjAzNmNlOTk6M2NkZDZlYTdmMjFkNGYwZGFiODI2YmJjMmQ2Zjg0NWE=
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials

###

GET https://api.spotify.com/v1/albums/2up3OPMp9Tb4dAKM2erWXQ
Authorization: Bearer {{token}}